<?php

return [
    'admin' => [
        'name' => 'modules.admin.name',
        'description' => 'modules.admin.description',
        'version' => '1.0.0',
        'category' => 'administration',
        'core' => true,
        'sellable' => false,
        'enabled_by_default' => true,
        'dependencies' => [],
        'permissions' => [
            'admin.access',
            'admin.settings.write',
            'admin.users.read',
            'admin.users.write',
        ],
    ],
    'api' => [
        'name' => 'modules.api.name',
        'description' => 'modules.api.description',
        'version' => '1.0.0',
        'category' => 'integration',
        'core' => true,
        'sellable' => false,
        'enabled_by_default' => true,
        'dependencies' => [],
        'permissions' => [
            'api.access',
            'api.keys.write',
        ],
    ],
    'licensing' => [
        'name' => 'modules.licensing.name',
        'description' => 'modules.licensing.description',
        'version' => '1.0.0',
        'category' => 'licensing',
        'core' => true,
        'sellable' => false,
        'enabled_by_default' => true,
        'dependencies' => [],
        'permissions' => [
            'licensing.status.read',
            'licensing.validate.write',
        ],
    ],
    'pdv' => [
        'name' => 'modules.pdv.name',
        'description' => 'modules.pdv.description',
        'version' => '1.0.0',
        'category' => 'operation',
        'core' => false,
        'sellable' => true,
        'enabled_by_default' => false,
        'dependencies' => ['printing'],
        'permissions' => [
            'pdv.access',
            'pdv.cashier.open',
            'pdv.cashier.close',
            'pdv.orders.create',
            'pdv.payments.write',
        ],
    ],
    'waiter' => [
        'name' => 'modules.waiter.name',
        'description' => 'modules.waiter.description',
        'version' => '1.0.0',
        'category' => 'operation',
        'core' => false,
        'sellable' => true,
        'enabled_by_default' => false,
        'dependencies' => ['api'],
        'permissions' => [
            'waiter.access',
            'waiter.orders.create',
            'waiter.tables.view',
        ],
    ],
    'kitchen' => [
        'name' => 'modules.kitchen.name',
        'description' => 'modules.kitchen.description',
        'version' => '1.0.0',
        'category' => 'operation',
        'core' => false,
        'sellable' => true,
        'enabled_by_default' => false,
        'dependencies' => ['printing'],
        'permissions' => [
            'kitchen.access',
            'kitchen.items.start',
            'kitchen.items.ready',
        ],
    ],
    'hall' => [
        'name' => 'modules.hall.name',
        'description' => 'modules.hall.description',
        'version' => '1.0.0',
        'category' => 'operation',
        'core' => false,
        'sellable' => true,
        'enabled_by_default' => false,
        'dependencies' => [],
        'permissions' => [
            'hall.access',
        ],
    ],
    'delivery' => [
        'name' => 'modules.delivery.name',
        'description' => 'modules.delivery.description',
        'version' => '1.0.0',
        'category' => 'sales',
        'core' => false,
        'sellable' => true,
        'enabled_by_default' => false,
        'dependencies' => ['api'],
        'permissions' => [
            'delivery.access',
            'delivery.orders.dispatch',
        ],
    ],
    'tablet_table' => [
        'name' => 'modules.tablet_table.name',
        'description' => 'modules.tablet_table.description',
        'version' => '1.0.0',
        'category' => 'sales',
        'core' => false,
        'sellable' => true,
        'enabled_by_default' => false,
        'dependencies' => ['api'],
        'permissions' => [
            'tablet_table.access',
            'tablet_table.orders.create',
        ],
    ],
    'kiosk' => [
        'name' => 'modules.kiosk.name',
        'description' => 'modules.kiosk.description',
        'version' => '1.0.0',
        'category' => 'sales',
        'core' => false,
        'sellable' => true,
        'enabled_by_default' => false,
        'dependencies' => ['api', 'printing'],
        'permissions' => [
            'kiosk.access',
        ],
    ],
    'digital_menu' => [
        'name' => 'modules.digital_menu.name',
        'description' => 'modules.digital_menu.description',
        'version' => '1.0.0',
        'category' => 'sales',
        'core' => false,
        'sellable' => true,
        'enabled_by_default' => false,
        'dependencies' => ['api'],
        'permissions' => [
            'digital_menu.access',
        ],
    ],
    'printing' => [
        'name' => 'modules.printing.name',
        'description' => 'modules.printing.description',
        'version' => '1.0.0',
        'category' => 'integration',
        'core' => false,
        'sellable' => true,
        'enabled_by_default' => true,
        'dependencies' => [],
        'permissions' => [
            'printing.queue.read',
            'printing.queue.write',
        ],
    ],
];
